### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Worldmap'

### ISSUE THREAD

**Issue by scheung38** [narenaryan/Wecko#1]
File "/Users/minminsanjose/PycharmProjects/Wecko/main.py", line 92, in country_map
    worldmap_chart = pygal.Worldmap()
AttributeError: 'module' object has no attribute 'Worldmap'

Not sure what that is?

**Comment by narenaryan** [comment]
Bro , Have you installed pygal properly? . If did that just can you tell me what is version name.

**Comment by scheung38** [comment]
pygal 2.0.1

**Comment by narenaryan** [comment]
Scheung ,try to install that project in virtualenv. Just run 
$ pip install -r requirement.txt  
before running project

Seems like problem with new pygal distribution. Use versions from requirement.txt

**Comment by scheung38** [comment]
Ok I will try and last time checked I had all requirements

**Comment by narenaryan** [comment]
Ok ,sure.
